import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import bird from '../public/img/bird.png';
const inter = Inter({ subsets: ['latin'] })

import TagIcon from '@mui/icons-material/Tag';
import SettingsIcon from '@mui/icons-material/Settings';
import SearchIcon from '@mui/icons-material/Search';
import SettingsOutlinedIcon from '@mui/icons-material/SettingsOutlined';
export default function Home() {
  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <div className="split-left left">
        <div className="">
          <div className="login-home-menu ">
            <div className=''>
              <div></div>
              
              <div className='login-body-menu-content' >
              <Image src={bird} alt="logo"  style={{width:"46px", height:"33px", borderRadius:"100px", marginLeft:"20px"}} />
                <div class="login-icon">
                  <button className='btn login-button'><TagIcon styles={{width:"10px"}}/>Explore</button>
                </div>
                <div class="login-icon">
                  <button className='btn login-button'><SettingsOutlinedIcon styles={{width:"10px"}}/> Settings</button>
                </div>
                
              </div>
            </div>

          </div>
        </div>
      </div>

      <div className="split-middle middle">
          <div>
            <div class="container">
                  <div class="search">
                    <SearchIcon className='fa-search'/>
                    <input type="text" class="form-control" placeholder="Search Twitter"/>
                    
                  </div>
                  <div className='search-bar-setting'>
                      <button className='btn btn-link'><SettingsOutlinedIcon styles={{width:"5px" }}/></button>
                  </div>   
            </div>
        </div>
        <div>
          <button className='section-button btn'>For you</button>
          <button className='section-button btn'>Trending</button>
          <button className='section-button btn'>News</button>
          <button className='section-button btn'>Sports</button>
          <button className='section-button btn'>Entertrainment</button>
        </div>
      </div>

      <div className="split-right right">
        <div className="">
          
          <div className='login-outerbox'>
          <div>
            <h5 className='new-to-twitter'>New to Twitter?</h5>
            <p className='login-body-homepage'>Sign up now to get your own personalized timeline!</p>
          </div>
            <button type="button" class="btn btn-light btn-lg btn-block custom-homeloginbutton">Sign up with Google</button>
            <button type="button" class="btn btn-light btn-lg btn-block custom-homeloginbutton">Sign up with Apple</button>
            <button type="button" class="btn btn-light btn-lg btn-block custom-homeloginbutton">create account</button>
            <p className='login-body-homepage'>By signing up, you agree to the <a href=''>Terms of Service</a> and <a href ="">Privacy Policy</a>, including <a href="">Cookie Use</a>.</p>
          </div>
          
        </div>
      </div>
      </main>
    </>
  )
}
